[package]
name = "cfmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfmt-macros = { path = "macros", version = "0.1.0" }

[workspace]
members = [
    "macros"
]
